# 障碍物配置文件
obstacles:
  - id: 1
    name: "vehicle_ahead"
    type: 1  # VEHICLE
    init_x: 78.0
    init_y: 181.2
    init_yaw: 2.98
    length: 3.2
    width: 1.8
    height: 1.6
    speed: 3.50  # m/s
    use_noise: false
    noise_stddev: 0.01
  
